project = ""
region = "europe-west3"
location = "EUROPE-WEST3"
service_account = "serviceAccount:???@???.iam.gserviceaccount.com"
env_mailgun_api_key = ""
env_mailgun_domain_name = ""
env_mail_receiver = ""
env_cdn_base_url = ""
